# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/FPGA/PYNQ-z2/SPAD_simulator/SPAD_simulator.srcs/sources_1/ip/bram_ip/bram_ip.xci
# IP: The module: 'bram_ip' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/FPGA/PYNQ-z2/SPAD_simulator/SPAD_simulator.gen/sources_1/ip/bram_ip/bram_ip_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_ip'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/FPGA/PYNQ-z2/SPAD_simulator/SPAD_simulator.srcs/sources_1/ip/bram_ip/bram_ip.xci
# IP: The module: 'bram_ip' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/FPGA/PYNQ-z2/SPAD_simulator/SPAD_simulator.gen/sources_1/ip/bram_ip/bram_ip_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_ip'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
